apiVersion: v1
kind: Pod
metadata:
  name: nginx-gagal
  labels:
    app: my_nginx
    version: v1
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    environtment: dev
